### ISSUE TITLE
Qual tecnologia vamos utilizar no front-end e por que?

### ISSUE THREAD

**Issue by eoSalinas** [Laranja-Mecanica/orange-portifolio#2]
E aí galera como vamos desenrolar esse front-end? Vamos usar React puro? Next.js ou outra stack?

**Comment by RabbitDeWitt** [comment]
Acreditamos que será melhor para esse projeto nós utilizarmos Next Js com Material UI.

**Comment by eoSalinas** [comment]
Fechouu, estou com vocês time! Vou concluir essa issue então!
