### ISSUE TITLE
Quais serão as primeiras telas que iremos codar?

### ISSUE THREAD

**Issue by eoSalinas** [Laranja-Mecanica/orange-portifolio#5]
Bom essa issue aqui foi aberta com intuito de debatermos para decidir qual será as 3 primeiras telas que vamos atacar...

**Comment by HenriqueMundim** [comment]
Minha opinião priorizar a tela de login e cadastro, pois são mais simples e extremamente parecidas

**Comment by eoSalinas** [comment]
Concordo com o @HenriqueMundim e acho que podemos fazer também a tela de meu portfólio, assim  já fecha as 3 telas.

**Comment by eoSalinas** [comment]
O time chegamos a conclusão em call de focarmos inicialmente nas telas de login, cadastro e meu portfólio!
