### ISSUE TITLE
Tela Add Projeto

### ISSUE THREAD

**Issue by Outro-Dev** [Laranja-Mecanica/orange-portifolio#6]

**Comment by RabbitDeWitt** [comment]
Acho que podemos dividir essa tela em algumas etapas:

- [x]  Componente Header
- [x]  Seção de perfil do usuario
- [x]  A busca por tags
- [x]  Seção dos projetos
- [x]  Implementação dos Modais
- [x]  Dialog para cadastramos o projeto
- [x]  Responsividade

**Comment by eoSalinas** [comment]
O projeto está evoluindooo! 🚀😁

**Comment by RabbitDeWitt** [comment]
Oh yeah!!! This team is on fireeee!!!!!!
